#! /bin/sh

FILE=$1
LINE_INDICATOR=$2
INSERT_TEXT=$3
OFFSET=$4

if [ ! -f $FILE ]
then
  echo "ERROR: \"$FILE\" dosen't exist!" 2>&1
  exit 1
fi

LINE=$(grep -nF "$LINE_INDICATOR" $FILE | cut -d ':' -f 1)
if [ ! $LINE ]
then
  echo "ERROR: \"$LINE_INDICATOR\" line dosen't exist!" 2>&1
  exit 2
fi

grep -F "$INSERT_TEXT" $FILE > /dev/null
if [ $? -eq 0 ]
then
  echo "ERROR: \"$INSERT_TEXT\" is already inserted!" 2>&1
  exit 3
fi

if [ $OFFSET ]
then
  LINE=$(( $LINE + $OFFSET ))
fi
if [ $LINE -lt 1 ]
then
  echo 'ERROR: LINE became negative or 0!' 2>&1
  exit 4
fi
if [ $LINE -gt $(cat $FILE | wc -l) ]
then
  echo "ERROR: LINE was over the number of lines of \"$FILE\"" 2>&1
  exit 4
fi

TEMPFILE=/tmp/$(date +%Y%m%d%H%M%S)-$FILE
cp $FILE $TEMPFILE
head -$(($LINE - 1)) $TEMPFILE > $FILE
echo $INSERT_TEXT >> $FILE
tail -n +$LINE $TEMPFILE >> $FILE
rm $TEMPFILE
